# Generated by Django 5.0a1 on 2023-10-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producttab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=20)),
                ("pname", models.CharField(max_length=20)),
                ("price", models.IntegerField()),
                ("stock", models.IntegerField()),
                ("description", models.TextField()),
            ],
        ),
    ]
